server:
  port: 4815
spring:
  application:
    name: clientfeign
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
eureka:
  client:
    service-url:
      defaultZone: http://localhost:4813/eureka/
  instance:
    prefer-ip-address: true
