server:
  port: 4817
spring:
  application:
    name: operations
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: GtMgSystem
    url: jdbc:mysql://localhost:3306/cafeteriamanagement?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: "074813"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:4813/eureka/
  instance:
    prefer-ip-address: true
mybatis:
  mapper-locations: classpath:repository/*.xml
  type-aliases-package: com.example.operations.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
